### PR TITLE
[fix] Here-documents: parse a “real” shell word (or close enough) after `<<`

### LINKED ISSUE #58: Parse error for here document using exclamation mark
```sh
#!/bin/sh

cat <<!HEREDOC!
hello
this
is
smth..
!HEREDOC!
```

Originally reported in bash-language-server: https://github.com/mads-hartmann/bash-language-server/issues/126

### PR DESCRIPTION
**Pull request by domq**
Fixes #58, #88 and #129.

### CODE REVIEW

**Comment by skovhus** [comment]
@domq awesome that you are looking into fixing these issues!

**Comment by domq** [comment]
Hello @maxbrunsfeld, would you be so kind as to review this?

**Comment by skovhus** [comment]
@verhovsky can you help here?

**Comment by skovhus** [comment]
@domq otherwise I'm considering if we should do a fork – your change here would improve https://github.com/bash-lsp/bash-language-server

**Comment by maxbrunsfeld** [comment]
Nice work @domq .

**Pull request merged**
