### PR TITLE
Publish package with GitHub Actions

### PR DESCRIPTION
**Pull request by verhovsky**

### CODE REVIEW

**Comment by skovhus** [comment]
This would be great @maxbrunsfeld and help solve https://github.com/tree-sitter/tree-sitter-bash/issues/134

**Comment by skovhus** [comment]
@verhovsky should this be merged? This would be great.

**Comment by verhovsky** [comment]
@skovhus as far as I know, @maxbrunsfeld is the only one who ran make releases. If this is merged it won't work until/unless he adds an npm API key. It is up to him if he wants this/if this will help him.

**Comment by verhovsky** [comment]
I see now that all of this has already been discussed and someone already proposed the exact same PR 3 months before this one

https://github.com/tree-sitter/tree-sitter/discussions/1768

https://github.com/tree-sitter/tree-sitter-java/pull/98

**Comment by verhovsky** [comment]
5 months later, I am older and wiser and understand what `prebuild` is and how to work with binaries with Node. I updated this PR to also `prebuild` the binaries through github actions and used these changes in my fork of tree-sitter-bash to publish [v0.0.3](https://github.com/curlconverter/tree-sitter-bash/releases/tag/v0.0.3) and prebuild it for Node on windows/mac/linux. I didn't try publishing a Rust crate.

**Pull request closed without merging**
