### PR TITLE
Handle empty default value during variable expansion

### PR DESCRIPTION
**Pull request by mads-hartmann**

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
It looks like you can also have a line feed but no space after the colon:

```sh
echo ${abc:
}
```

So maybe we should just make the expression after the colon `optional`. Thoughts?

**Comment by mads-hartmann** [comment]
@maxbrunsfeld Sure thing, I'll make the change :)

**Comment by maxbrunsfeld** [comment]
Thanks @mads-hartmann! Nice work!

**Comment by mads-hartmann** [comment]
@maxbrunsfeld No problem! :)

**Pull request merged**
