### PR TITLE
Gentoo fixes

### LINKED ISSUE #208: No handling for arithmetic operators precedence
```sh
echo "$(( 1 + 2 * 3 ))"
```

image

### LINKED ISSUE #210: Multiline string entirely misses its content
```sh
REPOS="
  main 
  restricted
  universe
"
```

image

I think there should be `string_content` nodes per line.

### LINKED ISSUE #213: Incorrect parsing when herestring is not at end
The following are all equivalent in bash, however only the first parses correctly
* `cmd arg <<<string` correctly results in
```
program [0, 0] - [1, 0]
  redirected_statement [0, 0] - [0, 17]
    body: command [0, 0] - [0, 7]
      name: command_name [0, 0] - [0, 3]
        word [0, 0] - [0, 3]
      argument: word [0, 4] - [0, 7]
    redirect: herestring_redirect [0, 8] - [0, 17]
      word [0, 11] - [0, 17]
```
* `cmd <<<string arg` results in:
```
program [0, 0] - [1, 0]
  redirected_statement [0, 0] - [0, 13]
    body: command [0, 0] - [0, 3]
      name: command_name [0, 0] - [0, 3]
        word [0, 0] - [0, 3]
    redirect: herestring_redirect [0, 4] - [0, 13]
      word [0, 7] - [0, 13]
  ERROR [0, 14] - [0, 17]
    word [0, 14] - [0, 17]
```
* `<<<string cmd arg` results in:
```
program [0, 0] - [1, 0]
  command [0, 0] - [0, 17]
    file_redirect [0, 0] - [0, 9]
      ERROR [0, 1] - [0, 3]
      destination: word [0, 3] - [0, 9]
    name: command_name [0, 10] - [0, 13]
      word [0, 10] - [0, 13]
    argument: word [0, 14] - [0, 17]
```

### PR DESCRIPTION
**Pull request by amaanq**
cc @thesamesam @arthurzam I'll keep working on this but you might be interested to monitor this anyways :)

Also, I'm graciously assuming this is a yes - but can I pluck snippets from Gentoo scripts for corpus tests here?

Closes #208 
Closes #210 
Closes #213

### CODE REVIEW

**Comment by thesamesam** [comment]
Woo!

I think snippets should be fine - ebuilds are GPL-2, but snippets are broadly going to be the kind of thing you'd get from #bash or other sites on the internet anyway, plus most of them are trivial in isolation.

https://www.gnu.org/licenses/gpl-faq.en.html#GPLFairUse and https://www.gnu.org/licenses/gpl-faq.en.html#SourceCodeInDocumentation suggests it should be OK. But if there's some particularly complex snippet (or if you want us to do it for any case you hit to feel more comfortable), we're happy to create small test cases as well.

**Comment by amaanq** [comment]
Awesome, thanks!

I think it should be okay, a lot of them are 1-liners that are useless alone and/or can be found in the wild - you can peruse the diff in any test/corpus/*.txt to check them out

**Comment by amaanq** [comment]
Down to 286 from 684

**Comment by arthurzam** [comment]
I'm very thankful for the huge work which is done here - I don't have words to describe my awe.

**Comment by amaanq** [comment]
I'm glad to hear!

I've had a lot of fun and annoyance fixing up expansions (majority of the failures w/ Gentoo files), and have pretty much embedded a parser inside the scanner for certain rules inside expansions - they're *very* annoying and Gentoo's corpus was very useful in figuring out how exactly it should be parsed.

There are a few files I simply cannot fix, they have to do w/ comments inside command substitutions, see the issues open about that. It'd just require a new mechanism upstream to handle. But that being said, I'm down to about 15 files failing otherwise

**Comment by amaanq** [comment]
Ok, seems to be just about done.

examples/gentoo/dev-util/qbs/qbs-1.19.1.ebuild                                                                                                                  0 ms    (ERROR [46, 11] - [120, 0])
examples/gentoo/mail-mta/courier/courier-1.1.5-r3.ebuild                                                                                                        2 ms    (ERROR [114, 51] - [114, 52])
examples/gentoo/mail-mta/courier/courier-1.2.3-r1.ebuild                                                                                                        1 ms    (ERROR [109, 51] - [109, 52])
examples/gentoo/mail-mta/courier/courier-1.3.3.ebuild                                                                                                           2 ms    (ERROR [109, 51] - [109, 52])
examples/gentoo/media-fonts/culmus/culmus-0.120-r6.ebuild                                                                                                       1 ms    (ERROR [169, 11] - [209, 0])
examples/gentoo/media-fonts/culmus/culmus-0.133-r1.ebuild                                                                                                       1 ms    (ERROR [171, 11] - [209, 0])
examples/gentoo/x11-libs/gtk+/gtk+-2.24.33-r3.ebuild                                                                                                            0 ms    (ERROR [285, 42] - [285, 45])

**Comment by amaanq** [comment]
@arthurzam @thesamesam if you can just review the tests I added to the corpus and see if they look okay from a licensing standpoint I'd be very appreciative

**Review by thesamesam — APPROVED** [review]
Looks fine to me, thanks a lot!

**Comment by amaanq** [comment]
Also, I'd like to add Gentoo's corpus, I accidentally did once in a commit here, and noticed it only took 4m to run compared to my local 8m (including cloning). It'll help a ton to catch regressions, imo the *scanner* is very delicate and I'd like to refactor some duplicate parts out into common functions/labels now that I know *how* stuff should be parsed, but that'll happen later. Grammar.js is much less delicate but still catching even *one* regression is something I'd like.

Adding it would be just adding the repo + commit hash in `script/parse-examples` :)

**Comment by arthurzam** [comment]
> Ok, seems to be just about done.
> 
> Failures:
> 
> examples/gentoo/dev-util/qbs/qbs-1.19.1.ebuild 0 ms (ERROR [46, 11] - [120, 0])  
> examples/gentoo/mail-mta/courier/courier-1.1.5-r3.ebuild 2 ms (ERROR [114, 51] - [114, 52])  
> examples/gentoo/mail-mta/courier/courier-1.2.3-r1.ebuild 1 ms (ERROR [109, 51] - [109, 52])  
> examples/gentoo/mail-mta/courier/courier-1.3.3.ebuild 2 ms (ERROR [109, 51] - [109, 52])  
> examples/gentoo/media-fonts/culmus/culmus-0.120-r6.ebuild 1 ms (ERROR [169, 11] - [209, 0])  
> examples/gentoo/media-fonts/culmus/culmus-0.133-r1.ebuild 1 ms (ERROR [171, 11] - [209, 0])  
> examples/gentoo/x11-libs/gtk+/gtk+-2.24.33-r3.ebuild 0 ms (ERROR [285, 42] - [285, 45]) 
> 

Yeah, this is a long history bash code repository, so some weird constructs can be expected. Maybe some of them can be just said - "not worth fixing". Do you have a way of marking errors as "do not fail job over those"?

This is a huge improvement over what we had so **thank you very much**.

> First one has a comment in a command sub

well, that was a weird hack. I think we can change the code to not use this hack.

> 2-4 have this monstrosity that the $ breaks:
> 
> ```
> word="`echo \"${2}\" | sed -e\"s|=.*$||\" -e\"s|^.*opt ||\"`"
> ```

I think we can look it up to try to improve this line.

> 5-6 has this: ` $((use fancy || use taamey) && echo ttf)` which is almost impossible to disambiguate between arithmetic expansions and command substitutions, shellcheck even warns about this: `Shells disambiguate $(( differently or not at all. For $(command substitution), add space after $( . For $((arithmetics)), fix parsing errors.`

I think we can fix it on our side, by adding a space `$( (` - the original is quite a risky code which could break one day.

> 7 has this: `[ -e "${EROOT}"/usr/lib/gtk-2.0/2.[^1]* ]`
> 
> which..feels bizarre. shellcheck says this: `-e doesn't work with globs. Use a for loop`. I'm not even sure how to parse this entirely

I think we should also fix it on our side.

**Review by arthurzam — APPROVED** [review]

**Comment by amaanq** [comment]
> Do you have a way of marking errors as "do not fail job over those"?

Yep, I'd just drop the file paths that fail in `script/known-failures.txt`

**Comment by thesamesam** [comment]
Yes - please do!

**Comment by amaanq** [comment]
@ObserverOfTime @ahlinc can you two look over and/or try out the last few commits related to string_content/heredoc_content being visible and the unary/binary expression precedence rework?

This is good to go otherwise

**Comment by arthurzam** [comment]
@amaanq we have pushed fixed version as https://github.com/gentoo/gentoo/commit/190ab28b73cc8f2e8f51fde63b494dd570f8cd2b
So would be nice to see the CI pass with gentoo :)

**Comment by amaanq** [comment]
Nice! Let me update locally and try it out - then update here

**Review by ObserverOfTime — APPROVED** [review]
LGTM

**Comment by ahlinc** [comment]
@amaanq https://github.com/tree-sitter/tree-sitter-bash/issues/210#issuecomment-1698732506

**Review by ahlinc — CHANGES_REQUESTED** [review]
Bugs described in #208 and #210 are reproducible on top of this branch.

**Comment by ahlinc** [comment]
@amaanq https://github.com/tree-sitter/tree-sitter-bash/issues/213#issuecomment-1698749246 is not fully correctly fixed too.

**Comment by ahlinc** [comment]
@amaanq May be in Gentoo repository it would be better to have no parsing errors and do fixes to avoid all complicated cases in the code, but for the parser impl I would ask you to open an issue with all hard parsing cases that are correct bash code, just for visibility of deficiencies and may be we'd figure out later how to handle them too.

**Comment by amaanq** [comment]
> Bugs described in #208 and #210 are reproducible on top of this branch.

Good catches - the herestring one was a hack, I completely reworked it now

String contents now also are separated per line

I had added precedences for c-style binary expressions, regular binary expressions, and expansion (length) binary expressions, but forgot the one the issue mentioned :laughing: which was arithmetic binary expressions. Should all be solved now

**Pull request merged**
