### PR TITLE
Support ANSII-C quoting in strings prefixed with $

### PR DESCRIPTION
**Pull request by nathansobo**
Refs https://github.com/atom/language-shellscript/issues/146

Bash [supports ANSII-C quoting in single-quoted strings that are prefixed with `$`](https://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html). For example, the string `$'Here\'s Johnny'` escapes the embedded single quote when prefixed with `$`. The expanded result is then treated as a single-quoted string.

To support this, I took my cue from `raw_string`, which is defined via a simple regex. I added a new symbol called `ansii_c_string` with a slightly more complex regular expression that allows escaped quotes single within the a string prefixed by `$`. One thing I wondered is whether this node should be aliased to `raw_string`, but it felt like that was adding complexity just to discard information from the tree, so I held off on it. Happy to adjust this though based on feedback.

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
This looks good to me. Thanks! I agree with your choice to keep it as a separate node type.

**Comment by maxbrunsfeld** [comment]
I think you have access to merge and publish now, but let me know if not.

**Comment by nathansobo** [comment]
Looks like I don't have permission to publish to npm.

```
npm ERR! 403 Forbidden - PUT https://registry.npmjs.org/tree-sitter-bash - You do not have permission to publish "tree-sitter-bash". Are you logged in as the correct user?
```

**Comment by nathansobo** [comment]
Published to npm as `tree-sitter-bash@0.16.0`

**Pull request merged**
