### PR TITLE
WIP: Add '>|' redirection to grammar

### PR DESCRIPTION
**Pull request by curusarn**
solves: https://github.com/tree-sitter/tree-sitter-bash/issues/63

### CODE REVIEW

**Comment by curusarn** [comment]
I have added `>|` redirection to the grammar. It seems unlikely to me that the following files should be edited by hand: 
- `src/grammar.json`
- `src/node-types.json`
- `src/parser.c`

I didn't find instructions on how to generate other files based on the grammar. Can somebody point me in the right direction? Are there more files that should be edited by hand?

**Comment by skovhus** [comment]
Thanks for the contribution!

> I didn't find instructions on how to generate other files based on the grammar. Can somebody point me in the right direction? Are there more files that should be edited by hand?

The grammar is generated by running `npx tree-sitter generate`.

One thing that is missing here is extending the test cases. This is done by updating the `corpus` files. In `corpus/commands.txt` the current redirection parsing is documented. You can add your case like this:

```
===============================
File redirects
===============================

whoami >| /dev/null
cat a b >| /dev/null

---

(program
  (redirected_statement
    (command (command_name (word)))
    (file_redirect (word)))
  (redirected_statement
    (command (command_name (word)) (word) (word))
    (file_redirect (word))))
```

Then once you run `npm test` you will see if your grammar works. Really nice workflow :)

I did the case above by simply copying the current `File redirects` and removing the last case. I skipped `2>|&1 whoami` as I'm not sure if that is valid bash syntax? If it is then there is an issue with the grammar.

**Comment by skovhus** [comment]
Note that this should be documented in the README (it was actually done in https://github.com/tree-sitter/tree-sitter-bash/pull/25), but I see that the commands broke due to some changes in https://github.com/tree-sitter/tree-sitter-bash/commit/2a3aec56355982c7550443cd71c0fb830699d084

**Comment by maxbrunsfeld** [comment]
The docs for developing these parsers are here: https://tree-sitter.github.io/tree-sitter/creating-parsers

**Comment by curusarn** [comment]
I've generated and committed the grammar.

I've added tests.

> I skipped `2>|&1 whoami` as I'm not sure if that is valid bash syntax?   

It's not a valid bash syntax - I skipped it in the tests.

**Comment by skovhus** [comment]
@maxbrunsfeld Anything we can do to land this?

**Comment by maxbrunsfeld** [comment]
Thanks @curusarn; great work!

**Pull request merged**
