### PR TITLE
Improve support for C-style for-loops

### PR DESCRIPTION
**Pull request by skovhus**
Work in progress. 

While browsing around in the known-errors (bash-it) I figured out that the C-style for-loops support has several bugs:
- does not support multiple variables assignments or updates (fixed)
- does not support spaces around variable assignments `for ((x = 0 ; x <= 100 ; x++));` is not parsed as an assignment, but a command with an error (not fixed)

@maxbrunsfeld I'm not sure how I should approach the last issue. It seems variable assignment support inside for loops might be different than normal assignments. Do I have any control over white space parsing inside grammar.js?

See https://wiki-dev.bash-hackers.org/syntax/ccmd/c_for for context

### CODE REVIEW

**Comment by skovhus** [comment]
I see now that there is some overlap with #55

**Comment by skovhus** [comment]
@maxbrunsfeld Let me know if you have any comments.

**Comment by maxbrunsfeld** [comment]
> It seems variable assignment support inside for loops might be different than normal assignments.

Yeah, it appears so. I think `x = y` will be handled currently by the `binary_expression` rule. Maybe we just need to add `variable_assignment` as an additional `choice` for the `initializer` (instead of replacing `_expression` with only `variable_assignment`).

Also, I don't think we should use `repeat($._expression)`, because that would mean you could have multiple expressions immediately following one another, like `i++ b++`. In reality, there needs to be a comma in between.

**Comment by skovhus** [comment]
Thanks. I’ll have another look.

**Pull request closed without merging**
